ejbs/src/jss/w08/bean/AppConfig.java
package jss.w08.bean;

import javax.ejb.EJBObject;

/**
 * @author Sergey Mikhluk.
 */
public interface AppConfig extends EJBObject {
}

ejbs/src/jss/w08/bean/AppConfigBean.java
package jss.w08.bean;

import javax.annotation.PostConstruct;
import javax.ejb.CreateException;
import javax.ejb.Singleton;
import javax.ejb.Startup;
import java.io.Serializable;
import java.util.Properties;

/**
 * @author Sergey Mikhluk.
 */

@Singleton(name = "AppConfigEJB")
@Startup
public class AppConfigBean implements Serializable {
    private Properties config;

    @PostConstruct
    public void init() {
        config = ConfigSingleton.getInstance().getConfig();
    }

    public Properties getConfig() {
        return config;
    }

    public void ejbCreate() throws CreateException {
    }
}

ejbs/src/jss/w08/bean/AppConfigHome.java
package jss.w08.bean;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * @author Sergey Mikhluk.
 */
public interface AppConfigHome extends EJBHome {
    jss.w08.bean.AppConfig create() throws RemoteException, CreateException;
}

ejbs/src/jss/w08/bean/ConfigSingleton.java
package jss.w08.bean;

import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.util.Properties;

/**
 * @author Sergey Mikhluk.
 */
public class ConfigSingleton implements Serializable{
    public static final String CONFIG_PATH = "db.properties";
    private Properties config = null;
    private static ConfigSingleton instance;

    private ConfigSingleton() {
        try {
            InputStream inputStream = this.getClass().getClassLoader().getResourceAsStream(CONFIG_PATH);
            config = new Properties();
            config.load(inputStream);
        } catch (IOException e) {
            e.printStackTrace();
        }
        //System.out.println("dbName: " + config.getProperty("dbName"));  //debug
    }

    public static ConfigSingleton getInstance() {
        if (instance == null) {
            instance = new ConfigSingleton();
        }
        return instance;
    }

    public Properties getConfig() {
        return config;
    }
}

ejbs/src/jss/w08/bean/DatabaseConnection.java
package jss.w08.bean;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Properties;

/**
 * @author Sergey Mikhluk.
 */
public class DatabaseConnection {
    // JDBC driver name and database URL
    private static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    private static final String DB_URL = "jdbc:mysql://localhost:3306/";
    private static final String DB_UNICODE = "?useUnicode=true&characterEncoding=utf8";
    // Database credentials
    private static final String USER = "user";
    private static final String PASS = "pass";

    private static DatabaseConnection instance = null;
    private static Connection conn = null;

    private DatabaseConnection(String dbName, String user, String pass) {
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL + dbName + DB_UNICODE, user, pass);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static Connection getConnection(String dbName) {

        if (instance == null) {
            instance = new DatabaseConnection(dbName, USER, PASS);
        }
        return instance.conn;
    }

    public static Connection getConnection(Properties conf) {
        if (instance == null) {
            instance = new DatabaseConnection(conf.getProperty("dbName"),
                    conf.getProperty("dbUser"), conf.getProperty("dbPass"));
        }
        return instance.conn;
    }

    public static Connection getConnection(String dbName, String user, String pass) {
        if (instance == null) {
            instance = new DatabaseConnection(dbName, user, pass);
        }
        return instance.conn;
    }
}

ejbs/src/jss/w08/bean/Filter.java
package jss.w08.bean;

import java.io.Serializable;
import java.util.HashMap;

/**
 * @author Sergey Mikhluk.
 */
public class Filter implements Serializable {

    public enum FilterConstant {
        PHOTO_ID("photo_id"),
        PHOTO_PATH("photo_path"),
        PHOTO_REGION_NAME("photo_region_name"),
        PERSON_ID("person_id"),
        PERSON_NAME("person_name");

        private String filterConstant;

        FilterConstant(String fConstant) {
            filterConstant = fConstant;
        }

        @Override
        public String toString() {
            return filterConstant;
        }
    }

    public Filter() {
    }


    private HashMap<String, String> data = new HashMap<>(100);

    public HashMap<String, String> getFilter() {
        return data;
    }

    public String getValue(String key) {
        String value = (data.get(key) == null) ? "" : data.get(key);
        return value;
    }

    public String getValue(FilterConstant key) {
        return getValue(key.toString());
    }

    public String getConstantValue(String key) {
        return FilterConstant.valueOf(key).toString();
    }

    public FilterConstant getConstant(String key) {
        return FilterConstant.valueOf(key);
    }

    public void setValueByKey(String key, String value) {
        data.put(key, value);
    }

    public void setValue(String key, String value) {
        data.put(getConstantValue(key), value);
    }

    public void setValue(FilterConstant key, String value) {
        data.put(key.toString(), value);
    }

}

src/net/javajoy/jss/homework/w07_test/beans/CalculatorBean.java
package net.javajoy.jss.homework.w07_test.beans;

import java.io.Serializable;

/**
 * @author Sergey Mikhluk.
 */
public class CalculatorBean implements Serializable {
    private double a = 0;
    private double b = 0;
    private String operation = "+";

    public CalculatorBean() {
    }

    public double getA() {
        return a;
    }

    public double getB() {
        return b;
    }

    public String getOperation() {
        return operation;
    }

    public double getResult(){
        double res = 0;
        switch (operation.charAt(0)) {
            case '+': res = a + b; break;
            case '-': res = a - b; break;
            case '*': res = a * b; break;
            case '/': res = a / b; break;
        }
        return res;
    }

    public void setA(double a) {
        this.a = a;
    }

    public void setB(double b) {
        this.b = b;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

    public void reset(){
        a = b = 0;
        operation = "+";
    }
}

src/net/javajoy/jss/homework/w07_test/beans/Figure.java
package net.javajoy.jss.homework.w07_test.beans;

/**
 * @author Sergey Mikhluk.
 */
public interface Figure {
    public int getSquare();

}

src/net/javajoy/jss/homework/w07_test/beans/PhotoDAO.java
package net.javajoy.jss.homework.w07_test.beans;

import javax.imageio.ImageIO;
import javax.servlet.http.HttpSession;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Sergey Mikhluk.
 * stored in session scope
 */
public class PhotoDAO {
    public static final String ATTRIBUTE_NAME = "PhotoDAO";
    private List<String> photoNames = new ArrayList<>(10);
    private List<byte[]> photoData = new ArrayList<>(10);

    public PhotoDAO(){
        try {
            BufferedImage img =  ImageIO.read(new File("D:\\13.jpg"));
            addPhoto("first", img);
            addPhoto("second", ImageIO.read(new File("D:\\13.jpg")));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void addPhoto(String name, byte[] data){
        photoNames.add(name);
        photoData.add(data);
    }

    public void addPhoto(String name, BufferedImage img){
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try {
            ImageIO.write(img, "jpg", bos);
            addPhoto("first", bos.toByteArray());
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    public List<String> getNamesAsList(){
        return photoNames;
    }

    public byte[] getPhotoData(int index){
        return photoData.get(index);
    }

    public String getPhotoName(int index){
        return photoNames.get(index);
    }

    public int getSize(){
        return photoData.size();
    }

    public static PhotoDAO getPhotoDAO(HttpSession session){
        PhotoDAO dao = (PhotoDAO) session.getAttribute(ATTRIBUTE_NAME);
        if (dao == null) {
            dao = new PhotoDAO();
            dao.addToSession(session);
        }

        return (PhotoDAO) session.getAttribute(ATTRIBUTE_NAME);

    }

    public void addToSession(HttpSession session) {
        session.setAttribute(ATTRIBUTE_NAME, this);
    }

    //removePhoto()



}

ejbClient/src/jss/w08/DBActionServlet.java
package jss.w08;

import jss.w08.dao.*;
import jss.w08.om.Person;
import jss.w08.om.Photo;

import javax.ejb.CreateException;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Part;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.rmi.RemoteException;

/**
 * @author Sergey Mikhluk.
 */

@WebServlet(name = "photoDBAction", urlPatterns = {"/photoDBAction"})
@MultipartConfig(location = "d:/temp", maxFileSize = 16 * 1024 * 1024, fileSizeThreshold = 0)
public class DBActionServlet extends HttpServlet {
    private InitialContext initialContext = null;

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        doGet(request, response);
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");
        String action = request.getParameter("action");
        String actionStatus;

        String photoId = request.getParameter("photo_id");
        if (photoId == null || photoId.equals("")) {
            actionStatus = "Wrong parameter photo_id!";

            // CK : Лучше в таких случаях делать перенаправление
            // на специальную страницу error.jsp, которая  actionStatus отобразит еще и пользователю
            // MS: исправил
            String refRedirect = String.format("jss/w08/error.jsp?&actionStatus=%s", actionStatus);
            response.sendRedirect(refRedirect);
            return;
        }
        Long id = new Long(photoId);

        actionStatus = "Wrong parameter action!";
        String refRedirect = String.format("jss/w08/error.jsp?&actionStatus=%s", actionStatus);
        if (action == null) {
            response.sendRedirect(refRedirect);
            return;
        }

        switch (action) {
            case "addPerson":
                actionStatus = actAddPerson(request, actionStatus);
                refRedirect = String.format("/ejbClient_war/openPersonPhoto?photo_id=%d&actionStatus=%s", id, actionStatus);
                break;

            case "deletePerson":
                Long personId = new Long(request.getParameter("person_id"));
                actionStatus = actDeletePerson(actionStatus, id, personId);
                refRedirect = String.format("/ejbClient_war/openPersonPhoto?photo_id=%d&actionStatus=%s", id, actionStatus);
                break;

            case "delete":
                actionStatus = actDelete(actionStatus, id);
                refRedirect = String.format("/ejbClient_war/openPhoto?photo_id=%d&actionStatus=%s", id, actionStatus);
                break;
            case "update":
                actionStatus = actUpdate(request, actionStatus);
                refRedirect = String.format("/ejbClient_war/openPhoto?photo_id=%d&actionStatus=%s", id, actionStatus);
                break;
            case "addPhoto":
                id = actAddPhoto(request);
                if (id > 0) {
                    actionStatus = "added";
                }
                refRedirect = String.format("/ejbClient_war/openPhoto?photo_id=%d&actionStatus=%s", id, actionStatus);
                break;
        }

        response.sendRedirect(refRedirect);
    }

    @Override
    public void init() throws ServletException {
        //super.init();
        // CK : получение контекста лучше вынести в init(), потому что этот метод вызывается многократно
        // MS: исправил
        try {
            initialContext = new InitialContext();
        } catch (NamingException e) {
            e.printStackTrace();
        }
    }

    private String actUpdate(HttpServletRequest request, String actionStatus) throws IOException, ServletException {
        boolean success;

        Photo photo = new Photo(request.getParameter("photo_id"), request.getParameter("updatePath"),
                request.getParameter("updateDate"), request.getParameter("updateRegionName"),
                request.getParameter("updateViews"), getImageDataFromPart(request));

        PhotoDAO photoDAO = getPhotoDAORef();
        success = photoDAO.update(photo);
        if (success) {
            actionStatus = "updated";
        }
        return actionStatus;
    }

    private PhotoDAO getPhotoDAORef() throws RemoteException {
        PhotoDAO photoDAO = null;
        try {
            // CK : получение контекста лучше вынести в init(), потому что этот метод вызывается многократно
            // MS: исправил
            photoDAO = ((PhotoDAOHome) initialContext.lookup("java:module/PhotoDAOEJB!jss.w08.dao.PhotoDAOHome")).create();
        } catch (NamingException | CreateException e) {
            e.printStackTrace();
        }
        return photoDAO;
    }

    private byte[] getImageDataFromPart(HttpServletRequest request) throws IOException, ServletException {
        Part filePart = request.getPart("file");
        InputStream inputStream = filePart.getInputStream();
        byte[] buf = new byte[1024*4];
        ByteArrayOutputStream bos = new ByteArrayOutputStream(1024*1024);
        while (inputStream.read(buf) > 0) {
            bos.write(buf);
        }
        return bos.toByteArray();
    }

    private String actDelete(String actionStatus, Long id) throws RemoteException{
        boolean success;

        PhotoDAO photoDAO = getPhotoDAORef();
        success = photoDAO.delete(id);
        if (success) {
            actionStatus = "deleted";
        }
        return actionStatus;
    }

    private Long actAddPhoto(HttpServletRequest request) throws ServletException, IOException {
        //System.out.println("DBActionServlet.java case addPhoto"); //debug
        Photo photo = new Photo(request.getParameter("photo_id"), request.getParameter("updatePath"),
                request.getParameter("updateDate"), request.getParameter("updateRegionName"),
                request.getParameter("updateViews"), getImageDataFromPart(request));

        PhotoDAO photoDAO = getPhotoDAORef();
        return photoDAO.add(photo);
    }

    private String actAddPerson(HttpServletRequest request, String actionStatus) {
        //System.out.println("DBActionServlet.java case addPerson"); // debug
        PersonDAOBean personDAO = new PersonDAOBean();
        Long id = personDAO.addPersonOnPhoto(Long.valueOf(request.getParameter("photo_id")), new Person(request.getParameter("updateName")));

        if (id > 0) {
            actionStatus = "added";
        }
        return actionStatus;
    }

    private String actDeletePerson(String actionStatus, Long photoId, Long personId) {
        //System.out.println("DBActionServlet.java case deletePerson");  //debug
        boolean success;

        PersonDAOBean personDAO = new PersonDAOBean();
        success = personDAO.deletePersonFromPhoto(photoId, personId);

        if (success) {
            actionStatus = "deleted";
        }
        return actionStatus;
    }
}

ejbClient/src/jss/w08/PhotoCardServlet.java
package jss.w08;

import jss.w08.dao.PhotoDAO;
import jss.w08.om.Photo;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * @author Sergey Mikhluk.
 */

@WebServlet(name = "PhotoCardServlet", urlPatterns = {"/photoCard"})
public class PhotoCardServlet extends HttpServlet {
    public static final int BUF_SIZE = 1024;

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        doGet(request, response);
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("image/jpeg");
        long id = Long.parseLong(request.getParameter("photo_id"));

        OutputStream binaryOut = response.getOutputStream();
        PhotoDAO photoDAO = (PhotoDAO) request.getSession().getAttribute("photoDAO");

        if (photoDAO != null) {
            Photo photo = photoDAO.getById(id);
            InputStream inputStream = photo.getDataInputStream();
            byte[] buf = new byte[BUF_SIZE];

            while (inputStream.read(buf) > 0) {
                binaryOut.write(buf);
            }

        } else {
            // error image
        }
    }
}

web/jss/w07_test/JSTLCalc.jsp
<%--
  Created by IntelliJ IDEA.
  User: Serg
  Date: 28.12.2015
  Time: 22:26
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

web/jss/w07_test/album.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="misctags" uri="http://javajoy.net/jss/miscTags" %>
<%--
  Created by IntelliJ IDEA.
  User: Serg
  Date: 10.01.2016
  Time: 22:22
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>User's Album</title>
</head>
<body>
    <jsp:useBean id="photoDAO" class="net.javajoy.jss.homework.w07_test.beans.PhotoDAO" scope="session"/>
    ${photoDAO.addToSession(pageContext.request.session)}
    <h3> Photos:</h3>
<table>
    <tr>
        <c:forEach var="i" begin="0" end="${photoDAO.size}">
            <td>
                <misctags:photoTag id="${i}"/>
            </td>
        </c:forEach>
    </tr>
    <tr>
        <c:forEach var="name" items ="${photoDAO.namesAsList}">
            <td>
                ${photoDAO.getPhotoName(i)}
            </td>
        </c:forEach>
    </tr>
    <tr>
        <c:forEach var="i" begin="0" end="${photoDAO.size}">
            <td>
                    <a href="/removePhotoServlet?id=${i}"> Remove</a>
            </td>
        </c:forEach>
    </tr>



</table>

<form action="/jss-sep-15-smikhluk/uploadPhoto" method="post" enctype="multipart/form-data">
    <input type="file" name="file" accept="image/jpeg"><br>
    <input type="submit" value="upload">
</form>



</body>
</html>

web/jss/w07_test/beansTest.jsp
<%--
  Created by IntelliJ IDEA.
  User: Serg
  Date: 09.01.2016
  Time: 21:43
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<html>
<head>
    <title>Beans Test</title>
</head>
<body>


    <h3> Calculator </h3>
    <jsp:useBean id="calc" class="net.javajoy.jss.homework.w07_test.beans.CalculatorBean" scope="session"/>
    <jsp:setProperty name="calc" property="a" value="15"/>
    <jsp:setProperty name="calc" property="b" value="3"/>
    <jsp:setProperty name="calc" property="operation" value="-"/>
    ${calc.a} ${calc.operation} ${calc.b} = ${calc.result} <br>
    ${calc.reset()}
    ${calc.result} <br>


    <h3> JavaBeen demo </h3>
    <jsp:useBean id="dateValue" class="java.util.Date"/>
    <jsp:setProperty name="dateValue" property="time" value="${pageContext.session.creationTime}"/>
    <fmt:formatDate value="${dateValue}" pattern="dd/MM/yyyy HH:mm:ss"/>
    <br>

    <jsp:setProperty name="dateValue" property="time" value="${pageContext.session.lastAccessedTime}"/>
    <fmt:formatDate value="${dateValue}" pattern="dd/MM/yyyy HH:mm:ss"/>

</body>
</html>

web/jss/w07_test/jstlCalc1.jsp
<%--
  Created by IntelliJ IDEA.
  User: Serg
  Date: 28.12.2015
  Time: 22:26
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<link rel="stylesheet" type="text/css" href="styles.css"/>
<html>
<head>
    <title>JSTL Calc</title>
</head>

<h2 class="header"> Calculator</h2>

<form method="get">
    <input type="text" name="a" size="10" value="${param.a}">
    <select name="operation" value="${param.operation}">
        <option value="+">Add</option>
        <option value="-">Subtract</option>
        <option value="*">Multiply</option>
        <option value="/">Divide</option>
    </select>
    <input type="text" name="b" size="10" value="${param.b}">

    <p></p>
    <input type="submit" value="Submit">
    <input type="reset" value="Reset">
</form>

<c:catch var="exception">
    <c:if test="${not empty param.a and not empty param.b and not empty param.operation}" var="testEmptyParam">
        <c:set var="a">
            <fmt:parseNumber value=""/>
        </c:set>
        <c:set var="result" value="0"/>
        <c:choose>
            <c:when test="${param.operation =='+'}">
                <c:set var="result" value="${0 + param.a + param.b}"/>
            </c:when>
            <c:when test="${param.operation =='-'}">
                <c:set var="result" value="${0 + param.a - param.b}"/>
            </c:when>
            <c:when test="${param.operation =='*'}">
                <c:set var="result" value="${0 + param.a * param.b}"/>
            </c:when>
            <c:when test="${param.operation =='/'}">
                <c:set var="result" value="${0 + param.a / param.b}"/>
            </c:when>
        </c:choose>
        <h2 class="result">Result: ${param.a} ${param.operation} ${param.b} = ${result}</h2>
    </c:if>
    <c:if test="${!testEmptyParam}">
        <h2> Eneter all data! </h2>
    </c:if>
</c:catch>
<c:if test="${not empty exception}">
    <h2> Error: ${exception}</h2>
</c:if>
</body>
</html>

web/jss/w07_test/jstlCustomTags.jsp
<%@ taglib prefix="misc" uri="http://javajoy.net/jss/miscTags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core_1_1" %>
<%--
  Created by IntelliJ IDEA.
  User: Serg
  Date: 09.01.2016
  Time: 22:52
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Custom tags</title>
</head>
<body>
<c:set var="var" value="pageScope->var"/>
<c:set var="var" value="sessionScope->var" scope="session"/>
<%
    out.println(pageContext.getAttribute("var", pageContext.PAGE_SCOPE) + "<br>");
    out.println(pageContext.getAttribute("var", pageContext.SESSION_SCOPE) + "<br>");
%>


<h3>Simple tag:</h3>
<misc:simpleTag/>

<h3>Tag</h3>
<table>
    <c:set var="n" value="3"/>
    <misc:iterationTag begin="1" end="${n}" var="item1">
        <tr> <td> ${item1} </td>  </tr>
    </misc:iterationTag>
</table>

</body>
</html>

web/jss/w07_test/jstlDemo1.jsp
<%--
  Created by IntelliJ IDEA.
  User: Serg
  Date: 28.12.2015
  Time: 10:19
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<html>
<head>
    <title>JSTL</title>
</head>
<body>
<c:forEach var="i" begin="0" end="9">
    ${0 + i + 2} &nbsp; &nbsp;
</c:forEach>


<c:set var="clientID" scope="page" value="11234"/>

<c:if test="${not empty param['clientID']}">
    <c:set var="clientID" scope="session">
        ${param["clientID"]}
    </c:set>
    set client id
</c:if>
${ empty param["clientID"]? 33:1}

Client ID (page) = ${pageScope.clientID}
Client ID (session) = ${sessionScope.clientID}

<c:remove var="clientID" scope="page"/>

Client ID (page) = ${pageScope.clientID}
Client ID (session) = ${sessionScope.clientID}


<%--Session--%>
<br>

<h3>Session</h3>
Is new session (v1): ${pageContext.session.isNew()}<br>
Is new session (v2): ${pageContext.session.isNew()}<br>
Attribute : ${pageContext.session.setAttribute("a","abc")}
${pageContext.session.getAttribute("a")} <br>
Parameter (v1): ${pageContext.request.getParameter("clientID")}<br>
Parameter (v2): ${param.clientID}

<h3>Headers</h3>
<%--<c:set var="headerNames" value="${header.keySet()}"/>--%>
<c:set var="headerNames" value="${pageContext.request.headerNames}"/>
<c:forEach var="name" items="${headerNames}">
    ${name} = ${header[name]}<br>

</c:forEach>

<br>

<h3>ForEach</h3>
<c:set var="items" value="2,3,6,99,adsfdf,ieirtum, kkkk, ttt, 22, fkjfdk, 44,4,5,1"/>
<c:forEach var="elem" items="${items}" begin="2" end="8" step="2" varStatus="status">
    ${elem}${status.last? "<br>":","}
</c:forEach>

<br>


</body>
</html>

web/jss/w07_test/jstlFunc.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="misc" uri="http://javajoy.net/jss/miscFunctions" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%--
  Created by IntelliJ IDEA.
  User: Serg
  Date: 08.01.2016
  Time: 17:46
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title> Functions </title>
</head>
<body>
    <h3> Standard </h3>

    <c:set var="str" value="abcdEF"/>
    ${fn:replace(fn:toLowerCase(str),"de","XXXXX")}
    <h3> Custom </h3>

    ${misc:concat("Abc","def")}
    <p></p>
    ${misc:map2String(header, "<br>", " : ")}
    <p></p>

    <fmt:setLocale value="ru_RU" scope ="session"/>
    <c:set var="newVar" value="abdc" scope="session"/>
        ${misc:map2String(sessionScope, "<br>", " : ")}


</body>
</html>

web/jss/w07_test/jstlProstoTags.jsp
<%@ taglib prefix="misc" uri="http://javajoy.net/jss/miscTags" %>
<%--
  Created by IntelliJ IDEA.
  User: Serg
  Date: 17.01.2016
  Time: 23:21
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>JSTL Prosto Tags</title>
</head>
<body>
<h3>Prosto tag</h3>
<misc:prostoTag/>
<misc:simpleTag/>

</body>
</html>